# Generated by mycc (x86-64 backend)
    .text

	.globl	_get_x
	.p2align	2
_get_x:
	sub	sp, sp, #48
	stp	x29, x30, [sp, #32]
	add	x29, sp, #32
Lget_x_0:
	adrp	x0, _x@PAGE
	add	x0, x0, _x@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #24]
	b	Lget_x_1
Lget_x_1:
	ldr	w0, [sp, #24]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #32]
	add	sp, sp, #48
	ret

	.globl	_get_y
	.p2align	2
_get_y:
	sub	sp, sp, #48
	stp	x29, x30, [sp, #32]
	add	x29, sp, #32
Lget_y_0:
	adrp	x0, _y@PAGE
	add	x0, x0, _y@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #24]
	b	Lget_y_1
Lget_y_1:
	ldr	w0, [sp, #24]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #32]
	add	sp, sp, #48
	ret

	.globl	_get_z
	.p2align	2
_get_z:
	sub	sp, sp, #48
	stp	x29, x30, [sp, #32]
	add	x29, sp, #32
Lget_z_0:
	adrp	x0, _z@PAGE
	add	x0, x0, _z@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #24]
	b	Lget_z_1
Lget_z_1:
	ldr	w0, [sp, #24]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #32]
	add	sp, sp, #48
	ret

	.globl	_test_shadow_basic
	.p2align	2
_test_shadow_basic:
	sub	sp, sp, #64
	stp	x29, x30, [sp, #48]
	add	x29, sp, #48
Ltest_shadow_basic_0:
	mov	x0, #42
	str	w0, [sp, #32]
	ldr	w0, [sp, #32]
	sxtw	x0, w0
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #40]
	b	Ltest_shadow_basic_1
Ltest_shadow_basic_1:
	ldr	w0, [sp, #40]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #48]
	add	sp, sp, #64
	ret

	.globl	_test_shadow_nested
	.p2align	2
_test_shadow_nested:
	sub	sp, sp, #144
	stp	x29, x30, [sp, #128]
	add	x29, sp, #128
Ltest_shadow_nested_0:
	mov	x0, #1
	str	w0, [sp, #112]
	mov	x0, #2
	str	w0, [sp, #104]
	mov	x0, #3
	str	w0, [sp, #96]
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	str	w0, [sp, #96]
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #24]
	ldr	x0, [sp, #24]
	str	w0, [sp, #96]
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #120]
	b	Ltest_shadow_nested_1
Ltest_shadow_nested_1:
	ldr	w0, [sp, #120]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #128]
	add	sp, sp, #144
	ret

	.globl	_test_shadow_loop
	.p2align	2
_test_shadow_loop:
	sub	sp, sp, #208
	stp	x29, x30, [sp, #192]
	add	x29, sp, #192
Ltest_shadow_loop_0:
	mov	x0, xzr
	str	w0, [sp, #176]
	mov	x0, xzr
	str	w0, [sp, #168]
	b	Ltest_shadow_loop_2
Ltest_shadow_loop_1:
	ldr	w0, [sp, #184]
	sxtw	x0, w0
	str	x0, [sp, #136]
	ldr	x0, [sp, #136]
	ldp	x29, x30, [sp, #192]
	add	sp, sp, #208
	ret
Ltest_shadow_loop_2:
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #128]
	ldr	x0, [sp, #128]
	mov	x1, #5
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #112]
	ldr	x0, [sp, #112]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #104]
	ldr	x0, [sp, #104]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	cbnz	x0, Ltest_shadow_loop_3
	b	Ltest_shadow_loop_5
Ltest_shadow_loop_3:
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #80]
	ldr	x0, [sp, #80]
	mov	x1, #2
	mul	x0, x0, x1
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	str	w0, [sp, #160]
	ldr	w0, [sp, #176]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	w0, [sp, #160]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	x0, [sp, #56]
	ldr	x1, [sp, #48]
	add	x0, x0, x1
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	str	w0, [sp, #176]
	b	Ltest_shadow_loop_4
Ltest_shadow_loop_4:
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #168]
	b	Ltest_shadow_loop_2
Ltest_shadow_loop_5:
	ldr	w0, [sp, #176]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #184]
	b	Ltest_shadow_loop_1

	.globl	_test_shadow_param
	.p2align	2
_test_shadow_param:
	sub	sp, sp, #80
	stp	x29, x30, [sp, #64]
	add	x29, sp, #64
	str	x0, [sp, #56]
Ltest_shadow_param_0:
	ldr	x0, [sp, #56]
	str	w0, [sp, #40]
	ldr	w0, [sp, #40]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #48]
	b	Ltest_shadow_param_1
Ltest_shadow_param_1:
	ldr	w0, [sp, #48]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #64]
	add	sp, sp, #80
	ret

	.globl	_test_nested_scopes
	.p2align	2
_test_nested_scopes:
	sub	sp, sp, #176
	stp	x29, x30, [sp, #160]
	add	x29, sp, #160
Ltest_nested_scopes_0:
	mov	x0, xzr
	str	w0, [sp, #144]
	mov	x0, #10
	str	w0, [sp, #136]
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #96]
	ldr	w0, [sp, #136]
	sxtw	x0, w0
	str	x0, [sp, #88]
	ldr	x0, [sp, #96]
	ldr	x1, [sp, #88]
	add	x0, x0, x1
	str	x0, [sp, #80]
	ldr	x0, [sp, #80]
	str	w0, [sp, #144]
	mov	x0, #20
	str	w0, [sp, #128]
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	w0, [sp, #128]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	x0, [sp, #64]
	ldr	x1, [sp, #56]
	add	x0, x0, x1
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	str	w0, [sp, #144]
	mov	x0, #30
	str	w0, [sp, #120]
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	w0, [sp, #120]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #144]
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #152]
	b	Ltest_nested_scopes_1
Ltest_nested_scopes_1:
	ldr	w0, [sp, #152]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #160]
	add	sp, sp, #176
	ret

	.globl	_test_loop_scope
	.p2align	2
_test_loop_scope:
	sub	sp, sp, #304
	stp	x29, x30, [sp, #288]
	add	x29, sp, #288
Ltest_loop_scope_0:
	mov	x0, xzr
	str	w0, [sp, #272]
	mov	x0, xzr
	str	w0, [sp, #264]
	b	Ltest_loop_scope_2
Ltest_loop_scope_1:
	ldr	w0, [sp, #280]
	sxtw	x0, w0
	str	x0, [sp, #224]
	ldr	x0, [sp, #224]
	ldp	x29, x30, [sp, #288]
	add	sp, sp, #304
	ret
Ltest_loop_scope_2:
	ldr	w0, [sp, #264]
	sxtw	x0, w0
	str	x0, [sp, #216]
	ldr	x0, [sp, #216]
	mov	x1, #3
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #200]
	ldr	x0, [sp, #200]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #192]
	ldr	x0, [sp, #192]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #176]
	ldr	x0, [sp, #176]
	cbnz	x0, Ltest_loop_scope_3
	b	Ltest_loop_scope_5
Ltest_loop_scope_3:
	mov	x0, xzr
	str	w0, [sp, #256]
	mov	x0, xzr
	str	w0, [sp, #248]
	b	Ltest_loop_scope_6
Ltest_loop_scope_4:
	ldr	w0, [sp, #264]
	sxtw	x0, w0
	str	x0, [sp, #152]
	ldr	x0, [sp, #152]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #136]
	ldr	x0, [sp, #136]
	str	w0, [sp, #264]
	b	Ltest_loop_scope_2
Ltest_loop_scope_5:
	ldr	w0, [sp, #272]
	sxtw	x0, w0
	str	x0, [sp, #128]
	ldr	x0, [sp, #128]
	str	w0, [sp, #280]
	b	Ltest_loop_scope_1
Ltest_loop_scope_6:
	ldr	w0, [sp, #248]
	sxtw	x0, w0
	str	x0, [sp, #120]
	ldr	w0, [sp, #264]
	sxtw	x0, w0
	str	x0, [sp, #112]
	ldr	x0, [sp, #120]
	ldr	x1, [sp, #112]
	cmp	x0, x1
	cset	x0, le
	str	x0, [sp, #104]
	ldr	x0, [sp, #104]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #96]
	ldr	x0, [sp, #96]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #80]
	ldr	x0, [sp, #80]
	cbnz	x0, Ltest_loop_scope_7
	b	Ltest_loop_scope_9
Ltest_loop_scope_7:
	ldr	w0, [sp, #256]
	sxtw	x0, w0
	str	x0, [sp, #72]
	ldr	w0, [sp, #248]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	x0, [sp, #72]
	ldr	x1, [sp, #64]
	add	x0, x0, x1
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	str	w0, [sp, #256]
	b	Ltest_loop_scope_8
Ltest_loop_scope_8:
	ldr	w0, [sp, #248]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	str	w0, [sp, #248]
	b	Ltest_loop_scope_6
Ltest_loop_scope_9:
	ldr	w0, [sp, #272]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	w0, [sp, #256]
	sxtw	x0, w0
	str	x0, [sp, #16]
	ldr	x0, [sp, #24]
	ldr	x1, [sp, #16]
	add	x0, x0, x1
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #272]
	b	Ltest_loop_scope_4

	.globl	_test_if_scope
	.p2align	2
_test_if_scope:
	sub	sp, sp, #208
	stp	x29, x30, [sp, #192]
	add	x29, sp, #192
	str	x0, [sp, #184]
Ltest_if_scope_0:
	ldr	x0, [sp, #184]
	str	w0, [sp, #144]
	mov	x0, xzr
	str	w0, [sp, #168]
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #120]
	mov	x0, xzr
	ldr	x1, [sp, #120]
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #112]
	ldr	x0, [sp, #112]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #104]
	ldr	x0, [sp, #104]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	cbnz	x0, Ltest_if_scope_2
	b	Ltest_if_scope_3
Ltest_if_scope_1:
	ldr	w0, [sp, #176]
	sxtw	x0, w0
	str	x0, [sp, #80]
	ldr	x0, [sp, #80]
	ldp	x29, x30, [sp, #192]
	add	sp, sp, #208
	ret
Ltest_if_scope_2:
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #72]
	ldr	x0, [sp, #72]
	mov	x1, #2
	mul	x0, x0, x1
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	str	w0, [sp, #160]
	ldr	w0, [sp, #160]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	str	w0, [sp, #168]
	b	Ltest_if_scope_4
Ltest_if_scope_3:
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	mov	x1, #3
	mul	x0, x0, x1
	str	x0, [sp, #24]
	ldr	x0, [sp, #24]
	str	w0, [sp, #152]
	ldr	w0, [sp, #152]
	sxtw	x0, w0
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #168]
	b	Ltest_if_scope_4
Ltest_if_scope_4:
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #176]
	b	Ltest_if_scope_1

	.globl	_test_shadow_multi
	.p2align	2
_test_shadow_multi:
	sub	sp, sp, #144
	stp	x29, x30, [sp, #128]
	add	x29, sp, #128
Ltest_shadow_multi_0:
	mov	x0, #1
	str	w0, [sp, #112]
	mov	x0, #2
	str	w0, [sp, #104]
	mov	x0, #3
	str	w0, [sp, #96]
	mov	x0, #4
	str	w0, [sp, #88]
	mov	x0, #5
	str	w0, [sp, #80]
	ldr	w0, [sp, #80]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	mov	x1, xzr
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #80]
	ldr	w0, [sp, #80]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #120]
	b	Ltest_shadow_multi_1
Ltest_shadow_multi_1:
	ldr	w0, [sp, #120]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #128]
	add	sp, sp, #144
	ret

	.globl	_test_global_access
	.p2align	2
_test_global_access:
	sub	sp, sp, #96
	stp	x29, x30, [sp, #80]
	add	x29, sp, #80
Ltest_global_access_0:
	adrp	x0, _x@PAGE
	add	x0, x0, _x@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #56]
	adrp	x0, _y@PAGE
	add	x0, x0, _y@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	x0, [sp, #56]
	ldr	x1, [sp, #40]
	add	x0, x0, x1
	str	x0, [sp, #32]
	adrp	x0, _z@PAGE
	add	x0, x0, _z@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #16]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #16]
	add	x0, x0, x1
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #72]
	b	Ltest_global_access_1
Ltest_global_access_1:
	ldr	w0, [sp, #72]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #80]
	add	sp, sp, #96
	ret

	.globl	_test_global_shadow
	.p2align	2
_test_global_shadow:
	sub	sp, sp, #96
	stp	x29, x30, [sp, #80]
	add	x29, sp, #80
Ltest_global_shadow_0:
	mov	x0, #100
	str	w0, [sp, #64]
	mov	x0, #200
	str	w0, [sp, #56]
	ldr	w0, [sp, #64]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	w0, [sp, #56]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #72]
	b	Ltest_global_shadow_1
Ltest_global_shadow_1:
	ldr	w0, [sp, #72]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #80]
	add	sp, sp, #96
	ret

	.globl	_counter_inc
	.p2align	2
_counter_inc:
	sub	sp, sp, #64
	stp	x29, x30, [sp, #48]
	add	x29, sp, #48
Lcounter_inc_0:
	adrp	x0, _counter_val@PAGE
	add	x0, x0, _counter_val@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	adrp	x1, _counter_val@PAGE
	add	x1, x1, _counter_val@PAGEOFF
	str	w0, [x1]
	b	Lcounter_inc_1
Lcounter_inc_1:
	ldp	x29, x30, [sp, #48]
	add	sp, sp, #64
	ret

	.globl	_counter_add
	.p2align	2
_counter_add:
	sub	sp, sp, #80
	stp	x29, x30, [sp, #64]
	add	x29, sp, #64
	str	x0, [sp, #56]
Lcounter_add_0:
	ldr	x0, [sp, #56]
	str	w0, [sp, #48]
	adrp	x0, _counter_val@PAGE
	add	x0, x0, _counter_val@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	w0, [sp, #48]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	adrp	x1, _counter_val@PAGE
	add	x1, x1, _counter_val@PAGEOFF
	str	w0, [x1]
	b	Lcounter_add_1
Lcounter_add_1:
	ldp	x29, x30, [sp, #64]
	add	sp, sp, #80
	ret

	.globl	_counter_get
	.p2align	2
_counter_get:
	sub	sp, sp, #48
	stp	x29, x30, [sp, #32]
	add	x29, sp, #32
Lcounter_get_0:
	adrp	x0, _counter_val@PAGE
	add	x0, x0, _counter_val@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #24]
	b	Lcounter_get_1
Lcounter_get_1:
	ldr	w0, [sp, #24]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #32]
	add	sp, sp, #48
	ret

	.globl	_counter_reset
	.p2align	2
_counter_reset:
	sub	sp, sp, #32
	stp	x29, x30, [sp, #16]
	add	x29, sp, #16
Lcounter_reset_0:
	mov	x0, xzr
	adrp	x1, _counter_val@PAGE
	add	x1, x1, _counter_val@PAGEOFF
	str	w0, [x1]
	b	Lcounter_reset_1
Lcounter_reset_1:
	ldp	x29, x30, [sp, #16]
	add	sp, sp, #32
	ret

	.globl	_test_global_mutation
	.p2align	2
_test_global_mutation:
	sub	sp, sp, #48
	stp	x29, x30, [sp, #32]
	add	x29, sp, #32
Ltest_global_mutation_0:
	bl	_counter_reset
	bl	_counter_inc
	bl	_counter_inc
	bl	_counter_inc
	mov	x0, #7
	bl	_counter_add
	bl	_counter_get
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #24]
	b	Ltest_global_mutation_1
Ltest_global_mutation_1:
	ldr	w0, [sp, #24]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #32]
	add	sp, sp, #48
	ret

	.globl	_test_for_var_scope
	.p2align	2
_test_for_var_scope:
	sub	sp, sp, #288
	stp	x29, x30, [sp, #272]
	add	x29, sp, #272
Ltest_for_var_scope_0:
	mov	x0, xzr
	str	w0, [sp, #256]
	mov	x0, xzr
	str	w0, [sp, #248]
	b	Ltest_for_var_scope_2
Ltest_for_var_scope_1:
	ldr	w0, [sp, #264]
	sxtw	x0, w0
	str	x0, [sp, #216]
	ldr	x0, [sp, #216]
	ldp	x29, x30, [sp, #272]
	add	sp, sp, #288
	ret
Ltest_for_var_scope_2:
	ldr	w0, [sp, #248]
	sxtw	x0, w0
	str	x0, [sp, #208]
	ldr	x0, [sp, #208]
	mov	x1, #5
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #192]
	ldr	x0, [sp, #192]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #184]
	ldr	x0, [sp, #184]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #168]
	ldr	x0, [sp, #168]
	cbnz	x0, Ltest_for_var_scope_3
	b	Ltest_for_var_scope_5
Ltest_for_var_scope_3:
	ldr	w0, [sp, #256]
	sxtw	x0, w0
	str	x0, [sp, #160]
	ldr	w0, [sp, #248]
	sxtw	x0, w0
	str	x0, [sp, #152]
	ldr	x0, [sp, #160]
	ldr	x1, [sp, #152]
	add	x0, x0, x1
	str	x0, [sp, #144]
	ldr	x0, [sp, #144]
	str	w0, [sp, #256]
	b	Ltest_for_var_scope_4
Ltest_for_var_scope_4:
	ldr	w0, [sp, #248]
	sxtw	x0, w0
	str	x0, [sp, #136]
	ldr	x0, [sp, #136]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #120]
	ldr	x0, [sp, #120]
	str	w0, [sp, #248]
	b	Ltest_for_var_scope_2
Ltest_for_var_scope_5:
	mov	x0, xzr
	str	w0, [sp, #240]
	b	Ltest_for_var_scope_6
Ltest_for_var_scope_6:
	ldr	w0, [sp, #240]
	sxtw	x0, w0
	str	x0, [sp, #104]
	ldr	x0, [sp, #104]
	mov	x1, #5
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #80]
	ldr	x0, [sp, #80]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	cbnz	x0, Ltest_for_var_scope_7
	b	Ltest_for_var_scope_9
Ltest_for_var_scope_7:
	ldr	w0, [sp, #256]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	w0, [sp, #240]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	x0, [sp, #56]
	ldr	x1, [sp, #48]
	add	x0, x0, x1
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	str	w0, [sp, #256]
	b	Ltest_for_var_scope_8
Ltest_for_var_scope_8:
	ldr	w0, [sp, #240]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #240]
	b	Ltest_for_var_scope_6
Ltest_for_var_scope_9:
	ldr	w0, [sp, #256]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #264]
	b	Ltest_for_var_scope_1

	.globl	_test_while_scope
	.p2align	2
_test_while_scope:
	sub	sp, sp, #208
	stp	x29, x30, [sp, #192]
	add	x29, sp, #192
Ltest_while_scope_0:
	mov	x0, #5
	str	w0, [sp, #176]
	mov	x0, xzr
	str	w0, [sp, #168]
	b	Ltest_while_scope_2
Ltest_while_scope_1:
	ldr	w0, [sp, #184]
	sxtw	x0, w0
	str	x0, [sp, #136]
	ldr	x0, [sp, #136]
	ldp	x29, x30, [sp, #192]
	add	sp, sp, #208
	ret
Ltest_while_scope_2:
	ldr	w0, [sp, #176]
	sxtw	x0, w0
	str	x0, [sp, #120]
	mov	x0, xzr
	ldr	x1, [sp, #120]
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #112]
	ldr	x0, [sp, #112]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #104]
	ldr	x0, [sp, #104]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	cbnz	x0, Ltest_while_scope_3
	b	Ltest_while_scope_5
Ltest_while_scope_3:
	ldr	w0, [sp, #176]
	sxtw	x0, w0
	str	x0, [sp, #80]
	ldr	w0, [sp, #176]
	sxtw	x0, w0
	str	x0, [sp, #72]
	ldr	x0, [sp, #80]
	ldr	x1, [sp, #72]
	mul	x0, x0, x1
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	str	w0, [sp, #160]
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	w0, [sp, #160]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	x0, [sp, #56]
	ldr	x1, [sp, #48]
	add	x0, x0, x1
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	str	w0, [sp, #168]
	ldr	w0, [sp, #176]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	mov	x1, #1
	sub	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #176]
	b	Ltest_while_scope_4
Ltest_while_scope_4:
	b	Ltest_while_scope_2
Ltest_while_scope_5:
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #184]
	b	Ltest_while_scope_1

	.globl	_compute_with_locals
	.p2align	2
_compute_with_locals:
	sub	sp, sp, #288
	stp	x29, x30, [sp, #272]
	add	x29, sp, #272
	str	x0, [sp, #264]
	str	x1, [sp, #256]
Lcompute_with_locals_0:
	ldr	x0, [sp, #264]
	str	w0, [sp, #200]
	ldr	x0, [sp, #256]
	str	w0, [sp, #192]
	ldr	w0, [sp, #200]
	sxtw	x0, w0
	str	x0, [sp, #184]
	ldr	w0, [sp, #192]
	sxtw	x0, w0
	str	x0, [sp, #176]
	ldr	x0, [sp, #184]
	ldr	x1, [sp, #176]
	add	x0, x0, x1
	str	x0, [sp, #168]
	ldr	x0, [sp, #168]
	str	w0, [sp, #240]
	ldr	w0, [sp, #200]
	sxtw	x0, w0
	str	x0, [sp, #160]
	ldr	w0, [sp, #192]
	sxtw	x0, w0
	str	x0, [sp, #152]
	ldr	x0, [sp, #160]
	ldr	x1, [sp, #152]
	sub	x0, x0, x1
	str	x0, [sp, #144]
	ldr	x0, [sp, #144]
	str	w0, [sp, #232]
	ldr	w0, [sp, #200]
	sxtw	x0, w0
	str	x0, [sp, #136]
	ldr	w0, [sp, #192]
	sxtw	x0, w0
	str	x0, [sp, #128]
	ldr	x0, [sp, #136]
	ldr	x1, [sp, #128]
	mul	x0, x0, x1
	str	x0, [sp, #120]
	ldr	x0, [sp, #120]
	str	w0, [sp, #224]
	ldr	w0, [sp, #240]
	sxtw	x0, w0
	str	x0, [sp, #112]
	ldr	w0, [sp, #232]
	sxtw	x0, w0
	str	x0, [sp, #104]
	ldr	x0, [sp, #112]
	ldr	x1, [sp, #104]
	add	x0, x0, x1
	str	x0, [sp, #96]
	ldr	x0, [sp, #96]
	str	w0, [sp, #216]
	ldr	w0, [sp, #216]
	sxtw	x0, w0
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	str	w0, [sp, #240]
	ldr	w0, [sp, #224]
	sxtw	x0, w0
	str	x0, [sp, #80]
	ldr	x0, [sp, #80]
	mov	x1, #2
	sdiv	x0, x0, x1
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	str	w0, [sp, #208]
	ldr	w0, [sp, #208]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	str	w0, [sp, #232]
	ldr	w0, [sp, #240]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	w0, [sp, #232]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	x0, [sp, #48]
	ldr	x1, [sp, #40]
	add	x0, x0, x1
	str	x0, [sp, #32]
	ldr	w0, [sp, #224]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #248]
	b	Lcompute_with_locals_1
Lcompute_with_locals_1:
	ldr	w0, [sp, #248]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #272]
	add	sp, sp, #288
	ret

	.globl	_test_param_shadow
	.p2align	2
_test_param_shadow:
	sub	sp, sp, #144
	stp	x29, x30, [sp, #128]
	add	x29, sp, #128
	str	x0, [sp, #120]
	str	x1, [sp, #112]
Ltest_param_shadow_0:
	ldr	x0, [sp, #120]
	str	w0, [sp, #80]
	ldr	x0, [sp, #112]
	str	w0, [sp, #72]
	mov	x0, #10
	str	w0, [sp, #96]
	mov	x0, #20
	str	w0, [sp, #88]
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	w0, [sp, #88]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	x0, [sp, #48]
	ldr	x1, [sp, #40]
	add	x0, x0, x1
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	str	w0, [sp, #96]
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	w0, [sp, #88]
	sxtw	x0, w0
	str	x0, [sp, #16]
	ldr	x0, [sp, #24]
	ldr	x1, [sp, #16]
	add	x0, x0, x1
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #104]
	b	Ltest_param_shadow_1
Ltest_param_shadow_1:
	ldr	w0, [sp, #104]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #128]
	add	sp, sp, #144
	ret

	.globl	_test_mixed_scope
	.p2align	2
_test_mixed_scope:
	sub	sp, sp, #224
	stp	x29, x30, [sp, #208]
	add	x29, sp, #208
Ltest_mixed_scope_0:
	mov	x0, #1
	str	w0, [sp, #192]
	mov	x0, #2
	str	w0, [sp, #184]
	mov	x0, #3
	str	w0, [sp, #176]
	ldr	w0, [sp, #192]
	sxtw	x0, w0
	str	x0, [sp, #128]
	ldr	w0, [sp, #184]
	sxtw	x0, w0
	str	x0, [sp, #120]
	ldr	x0, [sp, #128]
	ldr	x1, [sp, #120]
	add	x0, x0, x1
	str	x0, [sp, #112]
	ldr	w0, [sp, #176]
	sxtw	x0, w0
	str	x0, [sp, #104]
	ldr	x0, [sp, #112]
	ldr	x1, [sp, #104]
	add	x0, x0, x1
	str	x0, [sp, #96]
	ldr	x0, [sp, #96]
	str	w0, [sp, #168]
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	mov	x1, #2
	mul	x0, x0, x1
	str	x0, [sp, #72]
	ldr	x0, [sp, #72]
	str	w0, [sp, #160]
	ldr	w0, [sp, #160]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	str	w0, [sp, #192]
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	str	w0, [sp, #184]
	ldr	w0, [sp, #192]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	w0, [sp, #184]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	x0, [sp, #48]
	ldr	x1, [sp, #40]
	add	x0, x0, x1
	str	x0, [sp, #32]
	ldr	w0, [sp, #176]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #200]
	b	Ltest_mixed_scope_1
Ltest_mixed_scope_1:
	ldr	w0, [sp, #200]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #208]
	add	sp, sp, #224
	ret

	.globl	_init_global_arr
	.p2align	2
_init_global_arr:
	sub	sp, sp, #192
	stp	x29, x30, [sp, #176]
	add	x29, sp, #176
Linit_global_arr_0:
	mov	x0, xzr
	str	w0, [sp, #168]
	b	Linit_global_arr_2
Linit_global_arr_1:
	ldp	x29, x30, [sp, #176]
	add	sp, sp, #192
	ret
Linit_global_arr_2:
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #152]
	ldr	x0, [sp, #152]
	mov	x1, #5
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #136]
	ldr	x0, [sp, #136]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #128]
	ldr	x0, [sp, #128]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #112]
	ldr	x0, [sp, #112]
	cbnz	x0, Linit_global_arr_3
	b	Linit_global_arr_5
Linit_global_arr_3:
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #104]
	ldr	x0, [sp, #104]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	mov	x1, #10
	mul	x0, x0, x1
	str	x0, [sp, #72]
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	mov	x1, #4
	mul	x0, x0, x1
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	sxtw	x0, w0
	str	x0, [sp, #32]
	adrp	x0, _global_arr@PAGE
	add	x0, x0, _global_arr@PAGEOFF
	ldr	x1, [sp, #32]
	add	x0, x0, x1
	str	x0, [sp, #24]
	ldr	x0, [sp, #72]
	ldr	x1, [sp, #24]
	str	w0, [x1]
	b	Linit_global_arr_4
Linit_global_arr_4:
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	str	w0, [sp, #168]
	b	Linit_global_arr_2
Linit_global_arr_5:
	b	Linit_global_arr_1

	.globl	_sum_global_arr
	.p2align	2
_sum_global_arr:
	sub	sp, sp, #224
	stp	x29, x30, [sp, #208]
	add	x29, sp, #208
Lsum_global_arr_0:
	mov	x0, xzr
	str	w0, [sp, #192]
	mov	x0, xzr
	str	w0, [sp, #184]
	b	Lsum_global_arr_2
Lsum_global_arr_1:
	ldr	w0, [sp, #200]
	sxtw	x0, w0
	str	x0, [sp, #160]
	ldr	x0, [sp, #160]
	ldp	x29, x30, [sp, #208]
	add	sp, sp, #224
	ret
Lsum_global_arr_2:
	ldr	w0, [sp, #184]
	sxtw	x0, w0
	str	x0, [sp, #152]
	ldr	x0, [sp, #152]
	mov	x1, #5
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #136]
	ldr	x0, [sp, #136]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #128]
	ldr	x0, [sp, #128]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #112]
	ldr	x0, [sp, #112]
	cbnz	x0, Lsum_global_arr_3
	b	Lsum_global_arr_5
Lsum_global_arr_3:
	ldr	w0, [sp, #192]
	sxtw	x0, w0
	str	x0, [sp, #104]
	ldr	w0, [sp, #184]
	sxtw	x0, w0
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	mov	x1, #4
	mul	x0, x0, x1
	str	x0, [sp, #72]
	ldr	x0, [sp, #72]
	sxtw	x0, w0
	str	x0, [sp, #64]
	adrp	x0, _global_arr@PAGE
	add	x0, x0, _global_arr@PAGEOFF
	ldr	x1, [sp, #64]
	add	x0, x0, x1
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	x0, [sp, #104]
	ldr	x1, [sp, #48]
	add	x0, x0, x1
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	str	w0, [sp, #192]
	b	Lsum_global_arr_4
Lsum_global_arr_4:
	ldr	w0, [sp, #184]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #184]
	b	Lsum_global_arr_2
Lsum_global_arr_5:
	ldr	w0, [sp, #192]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #200]
	b	Lsum_global_arr_1

	.globl	_test_complex_nesting
	.p2align	2
_test_complex_nesting:
	sub	sp, sp, #416
	stp	x29, x30, [sp, #400]
	add	x29, sp, #400
	str	x0, [sp, #392]
Ltest_complex_nesting_0:
	ldr	x0, [sp, #392]
	str	w0, [sp, #328]
	mov	x0, xzr
	str	w0, [sp, #376]
	mov	x0, xzr
	str	w0, [sp, #368]
	b	Ltest_complex_nesting_2
Ltest_complex_nesting_1:
	ldr	w0, [sp, #384]
	sxtw	x0, w0
	str	x0, [sp, #304]
	ldr	x0, [sp, #304]
	ldp	x29, x30, [sp, #400]
	add	sp, sp, #416
	ret
Ltest_complex_nesting_2:
	ldr	w0, [sp, #368]
	sxtw	x0, w0
	str	x0, [sp, #296]
	ldr	w0, [sp, #328]
	sxtw	x0, w0
	str	x0, [sp, #288]
	ldr	x0, [sp, #296]
	ldr	x1, [sp, #288]
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #280]
	ldr	x0, [sp, #280]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #272]
	ldr	x0, [sp, #272]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #256]
	ldr	x0, [sp, #256]
	cbnz	x0, Ltest_complex_nesting_3
	b	Ltest_complex_nesting_5
Ltest_complex_nesting_3:
	ldr	w0, [sp, #368]
	sxtw	x0, w0
	str	x0, [sp, #248]
	ldr	x0, [sp, #248]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #232]
	ldr	x0, [sp, #232]
	str	w0, [sp, #360]
	mov	x0, xzr
	str	w0, [sp, #352]
	b	Ltest_complex_nesting_6
Ltest_complex_nesting_4:
	ldr	w0, [sp, #368]
	sxtw	x0, w0
	str	x0, [sp, #216]
	ldr	x0, [sp, #216]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #200]
	ldr	x0, [sp, #200]
	str	w0, [sp, #368]
	b	Ltest_complex_nesting_2
Ltest_complex_nesting_5:
	ldr	w0, [sp, #376]
	sxtw	x0, w0
	str	x0, [sp, #192]
	ldr	x0, [sp, #192]
	str	w0, [sp, #384]
	b	Ltest_complex_nesting_1
Ltest_complex_nesting_6:
	ldr	w0, [sp, #352]
	sxtw	x0, w0
	str	x0, [sp, #184]
	ldr	w0, [sp, #360]
	sxtw	x0, w0
	str	x0, [sp, #176]
	ldr	x0, [sp, #184]
	ldr	x1, [sp, #176]
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #168]
	ldr	x0, [sp, #168]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #160]
	ldr	x0, [sp, #160]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #144]
	ldr	x0, [sp, #144]
	cbnz	x0, Ltest_complex_nesting_7
	b	Ltest_complex_nesting_9
Ltest_complex_nesting_7:
	ldr	w0, [sp, #352]
	sxtw	x0, w0
	str	x0, [sp, #136]
	ldr	x0, [sp, #136]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #120]
	ldr	x0, [sp, #120]
	str	w0, [sp, #344]
	ldr	w0, [sp, #344]
	sxtw	x0, w0
	str	x0, [sp, #104]
	mov	x0, xzr
	ldr	x1, [sp, #104]
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #96]
	ldr	x0, [sp, #96]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #72]
	ldr	x0, [sp, #72]
	cbnz	x0, Ltest_complex_nesting_10
	b	Ltest_complex_nesting_11
Ltest_complex_nesting_8:
	ldr	w0, [sp, #352]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	mov	x1, #1
	add	x0, x0, x1
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	str	w0, [sp, #352]
	b	Ltest_complex_nesting_6
Ltest_complex_nesting_9:
	b	Ltest_complex_nesting_4
Ltest_complex_nesting_10:
	ldr	w0, [sp, #360]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	w0, [sp, #344]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #40]
	ldr	x1, [sp, #32]
	mul	x0, x0, x1
	str	x0, [sp, #24]
	ldr	x0, [sp, #24]
	str	w0, [sp, #336]
	ldr	w0, [sp, #376]
	sxtw	x0, w0
	str	x0, [sp, #16]
	ldr	w0, [sp, #336]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #16]
	ldr	x1, [sp, #8]
	add	x0, x0, x1
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	str	w0, [sp, #376]
	b	Ltest_complex_nesting_11
Ltest_complex_nesting_11:
	b	Ltest_complex_nesting_8

	.globl	_test_sequential_blocks
	.p2align	2
_test_sequential_blocks:
	sub	sp, sp, #176
	stp	x29, x30, [sp, #160]
	add	x29, sp, #160
Ltest_sequential_blocks_0:
	mov	x0, xzr
	str	w0, [sp, #144]
	mov	x0, #10
	str	w0, [sp, #136]
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #96]
	ldr	w0, [sp, #136]
	sxtw	x0, w0
	str	x0, [sp, #88]
	ldr	x0, [sp, #96]
	ldr	x1, [sp, #88]
	add	x0, x0, x1
	str	x0, [sp, #80]
	ldr	x0, [sp, #80]
	str	w0, [sp, #144]
	mov	x0, #20
	str	w0, [sp, #128]
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	w0, [sp, #128]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	x0, [sp, #64]
	ldr	x1, [sp, #56]
	add	x0, x0, x1
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	str	w0, [sp, #144]
	mov	x0, #30
	str	w0, [sp, #120]
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	w0, [sp, #120]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #144]
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #152]
	b	Ltest_sequential_blocks_1
Ltest_sequential_blocks_1:
	ldr	w0, [sp, #152]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #160]
	add	sp, sp, #176
	ret

	.globl	_acc_add
	.p2align	2
_acc_add:
	sub	sp, sp, #80
	stp	x29, x30, [sp, #64]
	add	x29, sp, #64
	str	x0, [sp, #56]
Lacc_add_0:
	ldr	x0, [sp, #56]
	str	w0, [sp, #48]
	adrp	x0, _accumulator@PAGE
	add	x0, x0, _accumulator@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	w0, [sp, #48]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	adrp	x1, _accumulator@PAGE
	add	x1, x1, _accumulator@PAGEOFF
	str	w0, [x1]
	b	Lacc_add_1
Lacc_add_1:
	ldp	x29, x30, [sp, #64]
	add	sp, sp, #80
	ret

	.globl	_acc_mul
	.p2align	2
_acc_mul:
	sub	sp, sp, #80
	stp	x29, x30, [sp, #64]
	add	x29, sp, #64
	str	x0, [sp, #56]
Lacc_mul_0:
	ldr	x0, [sp, #56]
	str	w0, [sp, #48]
	adrp	x0, _accumulator@PAGE
	add	x0, x0, _accumulator@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	w0, [sp, #48]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	mul	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	adrp	x1, _accumulator@PAGE
	add	x1, x1, _accumulator@PAGEOFF
	str	w0, [x1]
	b	Lacc_mul_1
Lacc_mul_1:
	ldp	x29, x30, [sp, #64]
	add	sp, sp, #80
	ret

	.globl	_acc_get
	.p2align	2
_acc_get:
	sub	sp, sp, #48
	stp	x29, x30, [sp, #32]
	add	x29, sp, #32
Lacc_get_0:
	adrp	x0, _accumulator@PAGE
	add	x0, x0, _accumulator@PAGEOFF
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #24]
	b	Lacc_get_1
Lacc_get_1:
	ldr	w0, [sp, #24]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #32]
	add	sp, sp, #48
	ret

	.globl	_acc_set
	.p2align	2
_acc_set:
	sub	sp, sp, #48
	stp	x29, x30, [sp, #32]
	add	x29, sp, #32
	str	x0, [sp, #24]
Lacc_set_0:
	ldr	x0, [sp, #24]
	str	w0, [sp, #16]
	ldr	w0, [sp, #16]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	adrp	x1, _accumulator@PAGE
	add	x1, x1, _accumulator@PAGEOFF
	str	w0, [x1]
	b	Lacc_set_1
Lacc_set_1:
	ldp	x29, x30, [sp, #32]
	add	sp, sp, #48
	ret

	.globl	_test_global_accumulator
	.p2align	2
_test_global_accumulator:
	sub	sp, sp, #80
	stp	x29, x30, [sp, #64]
	add	x29, sp, #64
Ltest_global_accumulator_0:
	mov	x0, #1
	bl	_acc_set
	mov	x0, #2
	bl	_acc_add
	mov	x0, #3
	bl	_acc_mul
	mov	x0, #4
	bl	_acc_add
	bl	_acc_get
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #56]
	b	Ltest_global_accumulator_1
Ltest_global_accumulator_1:
	ldr	w0, [sp, #56]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #64]
	add	sp, sp, #80
	ret

	.globl	_main
	.p2align	2
_main:
	sub	sp, sp, #240
	stp	x29, x30, [sp, #224]
	add	x29, sp, #224
Lmain_0:
	bl	_test_shadow_basic
	str	x0, [sp, #168]
	ldr	x0, [sp, #168]
	str	w0, [sp, #208]
	bl	_get_x
	str	x0, [sp, #160]
	ldr	x0, [sp, #160]
	str	w0, [sp, #200]
	bl	_init_global_arr
	bl	_sum_global_arr
	str	x0, [sp, #152]
	ldr	x0, [sp, #152]
	mov	x1, #3
	sdiv	x0, x0, x1
	str	x0, [sp, #136]
	ldr	x0, [sp, #136]
	mov	x1, #2
	mul	x0, x0, x1
	str	x0, [sp, #120]
	ldr	x0, [sp, #120]
	str	w0, [sp, #192]
	mov	x0, #3
	bl	_test_complex_nesting
	str	x0, [sp, #104]
	ldr	x0, [sp, #104]
	mov	x1, #4
	sdiv	x0, x0, x1
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	str	w0, [sp, #184]
	bl	_test_while_scope
	str	x0, [sp, #80]
	ldr	x0, [sp, #80]
	str	w0, [sp, #176]
	ldr	w0, [sp, #208]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	w0, [sp, #200]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	w0, [sp, #192]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	w0, [sp, #184]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	w0, [sp, #176]
	sxtw	x0, w0
	str	x0, [sp, #32]
	adrp	x0, _.Lstr.0@PAGE
	add	x0, x0, _.Lstr.0@PAGEOFF
	ldr	x9, [sp, #64]
	ldr	x10, [sp, #56]
	ldr	x11, [sp, #48]
	ldr	x12, [sp, #40]
	ldr	x13, [sp, #32]
	sub	sp, sp, #48
	str	x9, [sp, #0]
	str	x10, [sp, #8]
	str	x11, [sp, #16]
	str	x12, [sp, #24]
	str	x13, [sp, #32]
	bl	_printf
	add	sp, sp, #48
	str	x0, [sp, #24]
	mov	x0, xzr
	str	w0, [sp, #216]
	b	Lmain_1
Lmain_1:
	ldr	w0, [sp, #216]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #224]
	add	sp, sp, #240
	ret

    .section __TEXT,__cstring,cstring_literals
_.Lstr.0:
    .asciz "%d %d %d %d %d\n\0"

    .globl _accumulator
    .zerofill __DATA,__bss,_accumulator,4,4
    .globl _global_arr
    .zerofill __DATA,__bss,_global_arr,8,8
    .globl _counter_val
    .zerofill __DATA,__bss,_counter_val,4,4
    .globl _z
    .zerofill __DATA,__bss,_z,4,4
    .globl _y
    .zerofill __DATA,__bss,_y,4,4
    .globl _x
    .zerofill __DATA,__bss,_x,4,4
.subsections_via_symbols
