# Generated by mycc (x86-64 backend)
    .text

	.globl	_add_myint
	.p2align	2
_add_myint:
	sub	sp, sp, #96
	stp	x29, x30, [sp, #80]
	add	x29, sp, #80
	str	x0, [sp, #72]
	str	x1, [sp, #64]
Ladd_myint_0:
	ldr	x0, [sp, #72]
	str	w0, [sp, #48]
	ldr	x0, [sp, #64]
	str	w0, [sp, #40]
	ldr	w0, [sp, #48]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	w0, [sp, #40]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #56]
	b	Ladd_myint_1
Ladd_myint_1:
	ldr	w0, [sp, #56]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #80]
	add	sp, sp, #96
	ret

	.globl	_compute_score
	.p2align	2
_compute_score:
	sub	sp, sp, #112
	stp	x29, x30, [sp, #96]
	add	x29, sp, #96
	str	x0, [sp, #88]
	str	x1, [sp, #80]
Lcompute_score_0:
	ldr	x0, [sp, #88]
	str	w0, [sp, #64]
	ldr	x0, [sp, #80]
	str	w0, [sp, #56]
	ldr	w0, [sp, #64]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	w0, [sp, #56]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	mov	x1, #2
	mul	x0, x0, x1
	str	x0, [sp, #24]
	ldr	x0, [sp, #48]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #72]
	b	Lcompute_score_1
Lcompute_score_1:
	ldr	w0, [sp, #72]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #96]
	add	sp, sp, #112
	ret

	.globl	_make_point
	.p2align	2
_make_point:
	sub	sp, sp, #96
	stp	x29, x30, [sp, #80]
	add	x29, sp, #80
	str	x0, [sp, #72]
	str	x1, [sp, #64]
Lmake_point_0:
	ldr	x0, [sp, #72]
	str	w0, [sp, #40]
	ldr	x0, [sp, #64]
	str	w0, [sp, #32]
	ldr	w0, [sp, #40]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #24]
	str	w0, [sp, #48]
	ldr	w0, [sp, #32]
	sxtw	x0, w0
	str	x0, [sp, #16]
	add	x0, sp, #48
	add	x0, x0, #4
	str	x0, [sp, #8]
	ldr	x0, [sp, #16]
	ldr	x1, [sp, #8]
	str	w0, [x1]
	add	x0, sp, #56
	add	x1, sp, #48
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	b	Lmake_point_1
Lmake_point_1:
	ldr	x0, [sp, #56]
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #80]
	add	sp, sp, #96
	ret

	.globl	_point_add
	.p2align	2
_point_add:
	sub	sp, sp, #144
	stp	x29, x30, [sp, #128]
	add	x29, sp, #128
	str	x0, [sp, #120]
	str	x1, [sp, #112]
Lpoint_add_0:
	add	x0, sp, #88
	ldr	x1, [sp, #120]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #80
	ldr	x1, [sp, #112]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w0, [sp, #88]
	sxtw	x0, w0
	str	x0, [sp, #72]
	ldr	w0, [sp, #80]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	x0, [sp, #72]
	ldr	x1, [sp, #64]
	add	x0, x0, x1
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	str	w0, [sp, #96]
	add	x0, sp, #88
	add	x0, x0, #4
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #40]
	add	x0, sp, #80
	add	x0, x0, #4
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #40]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	add	x0, sp, #96
	add	x0, x0, #4
	str	x0, [sp, #8]
	ldr	x0, [sp, #16]
	ldr	x1, [sp, #8]
	str	w0, [x1]
	add	x0, sp, #104
	add	x1, sp, #96
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	b	Lpoint_add_1
Lpoint_add_1:
	ldr	x0, [sp, #104]
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #128]
	add	sp, sp, #144
	ret

	.globl	_point_sub
	.p2align	2
_point_sub:
	sub	sp, sp, #144
	stp	x29, x30, [sp, #128]
	add	x29, sp, #128
	str	x0, [sp, #120]
	str	x1, [sp, #112]
Lpoint_sub_0:
	add	x0, sp, #88
	ldr	x1, [sp, #120]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #80
	ldr	x1, [sp, #112]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w0, [sp, #88]
	sxtw	x0, w0
	str	x0, [sp, #72]
	ldr	w0, [sp, #80]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	x0, [sp, #72]
	ldr	x1, [sp, #64]
	sub	x0, x0, x1
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	str	w0, [sp, #96]
	add	x0, sp, #88
	add	x0, x0, #4
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #40]
	add	x0, sp, #80
	add	x0, x0, #4
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #40]
	ldr	x1, [sp, #24]
	sub	x0, x0, x1
	str	x0, [sp, #16]
	add	x0, sp, #96
	add	x0, x0, #4
	str	x0, [sp, #8]
	ldr	x0, [sp, #16]
	ldr	x1, [sp, #8]
	str	w0, [x1]
	add	x0, sp, #104
	add	x1, sp, #96
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	b	Lpoint_sub_1
Lpoint_sub_1:
	ldr	x0, [sp, #104]
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #128]
	add	sp, sp, #144
	ret

	.globl	_point_scale
	.p2align	2
_point_scale:
	sub	sp, sp, #144
	stp	x29, x30, [sp, #128]
	add	x29, sp, #128
	str	x0, [sp, #120]
	str	x1, [sp, #112]
Lpoint_scale_0:
	add	x0, sp, #88
	ldr	x1, [sp, #120]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x0, [sp, #112]
	str	w0, [sp, #80]
	ldr	w0, [sp, #88]
	sxtw	x0, w0
	str	x0, [sp, #72]
	ldr	w0, [sp, #80]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	x0, [sp, #72]
	ldr	x1, [sp, #64]
	mul	x0, x0, x1
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	str	w0, [sp, #96]
	add	x0, sp, #88
	add	x0, x0, #4
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	w0, [sp, #80]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #40]
	ldr	x1, [sp, #32]
	mul	x0, x0, x1
	str	x0, [sp, #24]
	add	x0, sp, #96
	add	x0, x0, #4
	str	x0, [sp, #16]
	ldr	x0, [sp, #24]
	ldr	x1, [sp, #16]
	str	w0, [x1]
	add	x0, sp, #104
	add	x1, sp, #96
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	b	Lpoint_scale_1
Lpoint_scale_1:
	ldr	x0, [sp, #104]
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #128]
	add	sp, sp, #144
	ret

	.globl	_point_dot
	.p2align	2
_point_dot:
	sub	sp, sp, #144
	stp	x29, x30, [sp, #128]
	add	x29, sp, #128
	str	x0, [sp, #120]
	str	x1, [sp, #112]
Lpoint_dot_0:
	add	x0, sp, #96
	ldr	x1, [sp, #120]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #88
	ldr	x1, [sp, #112]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #80]
	ldr	w0, [sp, #88]
	sxtw	x0, w0
	str	x0, [sp, #72]
	ldr	x0, [sp, #80]
	ldr	x1, [sp, #72]
	mul	x0, x0, x1
	str	x0, [sp, #64]
	add	x0, sp, #96
	add	x0, x0, #4
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #48]
	add	x0, sp, #88
	add	x0, x0, #4
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #48]
	ldr	x1, [sp, #32]
	mul	x0, x0, x1
	str	x0, [sp, #24]
	ldr	x0, [sp, #64]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #104]
	b	Lpoint_dot_1
Lpoint_dot_1:
	ldr	w0, [sp, #104]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #128]
	add	sp, sp, #144
	ret

	.globl	_point_cross
	.p2align	2
_point_cross:
	sub	sp, sp, #144
	stp	x29, x30, [sp, #128]
	add	x29, sp, #128
	str	x0, [sp, #120]
	str	x1, [sp, #112]
Lpoint_cross_0:
	add	x0, sp, #96
	ldr	x1, [sp, #120]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #88
	ldr	x1, [sp, #112]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #80]
	add	x0, sp, #88
	add	x0, x0, #4
	str	x0, [sp, #72]
	ldr	x0, [sp, #72]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	x0, [sp, #80]
	ldr	x1, [sp, #64]
	mul	x0, x0, x1
	str	x0, [sp, #56]
	add	x0, sp, #96
	add	x0, x0, #4
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	w0, [sp, #88]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #40]
	ldr	x1, [sp, #32]
	mul	x0, x0, x1
	str	x0, [sp, #24]
	ldr	x0, [sp, #56]
	ldr	x1, [sp, #24]
	sub	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #104]
	b	Lpoint_cross_1
Lpoint_cross_1:
	ldr	w0, [sp, #104]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #128]
	add	sp, sp, #144
	ret

	.globl	_point_dist_sq
	.p2align	2
_point_dist_sq:
	sub	sp, sp, #208
	stp	x29, x30, [sp, #192]
	add	x29, sp, #192
	str	x0, [sp, #184]
	str	x1, [sp, #176]
Lpoint_dist_sq_0:
	add	x0, sp, #144
	ldr	x1, [sp, #184]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #136
	ldr	x1, [sp, #176]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w0, [sp, #144]
	sxtw	x0, w0
	str	x0, [sp, #128]
	ldr	w0, [sp, #136]
	sxtw	x0, w0
	str	x0, [sp, #120]
	ldr	x0, [sp, #128]
	ldr	x1, [sp, #120]
	sub	x0, x0, x1
	str	x0, [sp, #112]
	ldr	x0, [sp, #112]
	str	w0, [sp, #160]
	add	x0, sp, #144
	add	x0, x0, #4
	str	x0, [sp, #104]
	ldr	x0, [sp, #104]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #96]
	add	x0, sp, #136
	add	x0, x0, #4
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #80]
	ldr	x0, [sp, #96]
	ldr	x1, [sp, #80]
	sub	x0, x0, x1
	str	x0, [sp, #72]
	ldr	x0, [sp, #72]
	str	w0, [sp, #152]
	ldr	w0, [sp, #160]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	w0, [sp, #160]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	x0, [sp, #64]
	ldr	x1, [sp, #56]
	mul	x0, x0, x1
	str	x0, [sp, #48]
	ldr	w0, [sp, #152]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	w0, [sp, #152]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #40]
	ldr	x1, [sp, #32]
	mul	x0, x0, x1
	str	x0, [sp, #24]
	ldr	x0, [sp, #48]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #168]
	b	Lpoint_dist_sq_1
Lpoint_dist_sq_1:
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #192]
	add	sp, sp, #208
	ret

	.globl	_point_equal
	.p2align	2
_point_equal:
	sub	sp, sp, #208
	stp	x29, x30, [sp, #192]
	add	x29, sp, #192
	str	x0, [sp, #184]
	str	x1, [sp, #176]
Lpoint_equal_0:
	add	x0, sp, #160
	ldr	x1, [sp, #184]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #152
	ldr	x1, [sp, #176]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w0, [sp, #160]
	sxtw	x0, w0
	str	x0, [sp, #144]
	ldr	w0, [sp, #152]
	sxtw	x0, w0
	str	x0, [sp, #136]
	ldr	x0, [sp, #144]
	ldr	x1, [sp, #136]
	cmp	x0, x1
	cset	x0, eq
	str	x0, [sp, #128]
	ldr	x0, [sp, #128]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #120]
	ldr	x0, [sp, #120]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #104]
	ldr	x0, [sp, #104]
	cbnz	x0, Lpoint_equal_2_phi
	mov	x9, xzr
	str	x9, [sp, #24]
	b	Lpoint_equal_3
Lpoint_equal_2_phi:
	b	Lpoint_equal_2
Lpoint_equal_1:
	ldr	w0, [sp, #168]
	sxtw	x0, w0
	str	x0, [sp, #96]
	ldr	x0, [sp, #96]
	ldp	x29, x30, [sp, #192]
	add	sp, sp, #208
	ret
Lpoint_equal_2:
	add	x0, sp, #160
	add	x0, x0, #4
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #80]
	add	x0, sp, #152
	add	x0, x0, #4
	str	x0, [sp, #72]
	ldr	x0, [sp, #72]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	x0, [sp, #80]
	ldr	x1, [sp, #64]
	cmp	x0, x1
	cset	x0, eq
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #32]
	ldr	x9, [sp, #32]
	str	x9, [sp, #24]
	b	Lpoint_equal_3
Lpoint_equal_3:
	ldr	x0, [sp, #24]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #168]
	b	Lpoint_equal_1

	.globl	_make_rect
	.p2align	2
_make_rect:
	sub	sp, sp, #192
	stp	x29, x30, [sp, #176]
	add	x29, sp, #176
	str	x0, [sp, #168]
	str	x1, [sp, #160]
	str	x2, [sp, #152]
	str	x3, [sp, #144]
Lmake_rect_0:
	ldr	x0, [sp, #168]
	str	w0, [sp, #104]
	ldr	x0, [sp, #160]
	str	w0, [sp, #96]
	ldr	x0, [sp, #152]
	str	w0, [sp, #88]
	ldr	x0, [sp, #144]
	str	w0, [sp, #80]
	ldr	w0, [sp, #104]
	sxtw	x0, w0
	str	x0, [sp, #72]
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	x0, [sp, #72]
	ldr	x1, [sp, #64]
	bl	_make_point
	str	x0, [sp, #56]
	add	x0, sp, #112
	add	x1, sp, #56
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w0, [sp, #88]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	w0, [sp, #80]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	x0, [sp, #48]
	ldr	x1, [sp, #40]
	bl	_make_point
	str	x0, [sp, #32]
	add	x0, sp, #112
	add	x0, x0, #8
	str	x0, [sp, #24]
	ldr	x0, [sp, #24]
	add	x1, sp, #32
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #128
	add	x1, sp, #112
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	b	Lmake_rect_1
Lmake_rect_1:
	ldr	x9, [sp, #128]
	str	x9, [sp, #8]
	ldr	x9, [sp, #136]
	str	x9, [sp, #16]
	ldr	x0, [sp, #8]
	ldr	x1, [sp, #16]
	ldp	x29, x30, [sp, #176]
	add	sp, sp, #192
	ret

	.globl	_rect_width
	.p2align	2
_rect_width:
	sub	sp, sp, #96
	stp	x29, x30, [sp, #80]
	add	x29, sp, #80
	str	x0, [sp, #64]
Lrect_width_0:
	add	x0, sp, #40
	ldr	x1, [sp, #64]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	add	x0, sp, #40
	add	x0, x0, #8
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	w0, [sp, #40]
	sxtw	x0, w0
	str	x0, [sp, #16]
	ldr	x0, [sp, #24]
	ldr	x1, [sp, #16]
	sub	x0, x0, x1
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #56]
	b	Lrect_width_1
Lrect_width_1:
	ldr	w0, [sp, #56]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #80]
	add	sp, sp, #96
	ret

	.globl	_rect_height
	.p2align	2
_rect_height:
	sub	sp, sp, #112
	stp	x29, x30, [sp, #96]
	add	x29, sp, #96
	str	x0, [sp, #80]
Lrect_height_0:
	add	x0, sp, #56
	ldr	x1, [sp, #80]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	add	x0, sp, #56
	add	x0, x0, #8
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	add	x0, x0, #4
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #32]
	add	x0, sp, #56
	add	x0, x0, #4
	str	x0, [sp, #24]
	ldr	x0, [sp, #24]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #16]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #16]
	sub	x0, x0, x1
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #72]
	b	Lrect_height_1
Lrect_height_1:
	ldr	w0, [sp, #72]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #96]
	add	sp, sp, #112
	ret

	.globl	_rect_area
	.p2align	2
_rect_area:
	sub	sp, sp, #96
	stp	x29, x30, [sp, #80]
	add	x29, sp, #80
	str	x0, [sp, #64]
Lrect_area_0:
	add	x0, sp, #40
	ldr	x1, [sp, #64]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	add	x0, sp, #40
	bl	_rect_width
	str	x0, [sp, #32]
	add	x0, sp, #40
	bl	_rect_height
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	mul	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #56]
	b	Lrect_area_1
Lrect_area_1:
	ldr	w0, [sp, #56]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #80]
	add	sp, sp, #96
	ret

	.globl	_rect_perimeter
	.p2align	2
_rect_perimeter:
	sub	sp, sp, #112
	stp	x29, x30, [sp, #96]
	add	x29, sp, #96
	str	x0, [sp, #80]
Lrect_perimeter_0:
	add	x0, sp, #56
	ldr	x1, [sp, #80]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	add	x0, sp, #56
	bl	_rect_width
	str	x0, [sp, #40]
	add	x0, sp, #56
	bl	_rect_height
	str	x0, [sp, #32]
	ldr	x0, [sp, #40]
	ldr	x1, [sp, #32]
	add	x0, x0, x1
	str	x0, [sp, #24]
	mov	x0, #2
	ldr	x1, [sp, #24]
	mul	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #72]
	b	Lrect_perimeter_1
Lrect_perimeter_1:
	ldr	w0, [sp, #72]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #96]
	add	sp, sp, #112
	ret

	.globl	_rect_contains_point
	.p2align	2
_rect_contains_point:
	sub	sp, sp, #432
	stp	x29, x30, [sp, #416]
	add	x29, sp, #416
	str	x0, [sp, #400]
	str	x1, [sp, #392]
Lrect_contains_point_0:
	add	x0, sp, #368
	ldr	x1, [sp, #400]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	add	x0, sp, #360
	ldr	x1, [sp, #392]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w0, [sp, #368]
	sxtw	x0, w0
	str	x0, [sp, #352]
	ldr	w0, [sp, #360]
	sxtw	x0, w0
	str	x0, [sp, #344]
	ldr	x0, [sp, #352]
	ldr	x1, [sp, #344]
	cmp	x0, x1
	cset	x0, le
	str	x0, [sp, #336]
	ldr	x0, [sp, #336]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #328]
	ldr	x0, [sp, #328]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #312]
	ldr	x0, [sp, #312]
	cbnz	x0, Lrect_contains_point_6_phi
	mov	x9, xzr
	str	x9, [sp, #40]
	b	Lrect_contains_point_7
Lrect_contains_point_6_phi:
	b	Lrect_contains_point_6
Lrect_contains_point_1:
	ldr	w0, [sp, #384]
	sxtw	x0, w0
	str	x0, [sp, #304]
	ldr	x0, [sp, #304]
	ldp	x29, x30, [sp, #416]
	add	sp, sp, #432
	ret
Lrect_contains_point_2:
	add	x0, sp, #360
	add	x0, x0, #4
	str	x0, [sp, #296]
	ldr	x0, [sp, #296]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #288]
	add	x0, sp, #368
	add	x0, x0, #8
	str	x0, [sp, #280]
	ldr	x0, [sp, #280]
	add	x0, x0, #4
	str	x0, [sp, #272]
	ldr	x0, [sp, #272]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #264]
	ldr	x0, [sp, #288]
	ldr	x1, [sp, #264]
	cmp	x0, x1
	cset	x0, le
	str	x0, [sp, #256]
	ldr	x0, [sp, #256]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #248]
	ldr	x0, [sp, #248]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #232]
	ldr	x9, [sp, #232]
	str	x9, [sp, #224]
	b	Lrect_contains_point_3
Lrect_contains_point_3:
	ldr	x0, [sp, #224]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #208]
	ldr	x0, [sp, #208]
	str	w0, [sp, #384]
	b	Lrect_contains_point_1
Lrect_contains_point_4:
	add	x0, sp, #368
	add	x0, x0, #4
	str	x0, [sp, #200]
	ldr	x0, [sp, #200]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #192]
	add	x0, sp, #360
	add	x0, x0, #4
	str	x0, [sp, #184]
	ldr	x0, [sp, #184]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #176]
	ldr	x0, [sp, #192]
	ldr	x1, [sp, #176]
	cmp	x0, x1
	cset	x0, le
	str	x0, [sp, #168]
	ldr	x0, [sp, #168]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #160]
	ldr	x0, [sp, #160]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #144]
	ldr	x9, [sp, #144]
	str	x9, [sp, #136]
	b	Lrect_contains_point_5
Lrect_contains_point_5:
	ldr	x0, [sp, #136]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #120]
	ldr	x0, [sp, #120]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #104]
	ldr	x0, [sp, #104]
	cbnz	x0, Lrect_contains_point_2_phi
	mov	x9, xzr
	str	x9, [sp, #224]
	b	Lrect_contains_point_3
Lrect_contains_point_2_phi:
	b	Lrect_contains_point_2
Lrect_contains_point_6:
	ldr	w0, [sp, #360]
	sxtw	x0, w0
	str	x0, [sp, #96]
	add	x0, sp, #368
	add	x0, x0, #8
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #80]
	ldr	x0, [sp, #96]
	ldr	x1, [sp, #80]
	cmp	x0, x1
	cset	x0, le
	str	x0, [sp, #72]
	ldr	x0, [sp, #72]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #48]
	ldr	x9, [sp, #48]
	str	x9, [sp, #40]
	b	Lrect_contains_point_7
Lrect_contains_point_7:
	ldr	x0, [sp, #40]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #24]
	ldr	x0, [sp, #24]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	cbnz	x0, Lrect_contains_point_4_phi
	mov	x9, xzr
	str	x9, [sp, #136]
	b	Lrect_contains_point_5
Lrect_contains_point_4_phi:
	b	Lrect_contains_point_4

	.globl	_rects_overlap
	.p2align	2
_rects_overlap:
	sub	sp, sp, #464
	stp	x29, x30, [sp, #448]
	add	x29, sp, #448
	str	x0, [sp, #432]
	str	x1, [sp, #416]
Lrects_overlap_0:
	add	x0, sp, #392
	ldr	x1, [sp, #432]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	add	x0, sp, #376
	ldr	x1, [sp, #416]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	add	x0, sp, #376
	add	x0, x0, #8
	str	x0, [sp, #368]
	ldr	x0, [sp, #368]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #360]
	ldr	w0, [sp, #392]
	sxtw	x0, w0
	str	x0, [sp, #352]
	ldr	x0, [sp, #360]
	ldr	x1, [sp, #352]
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #344]
	ldr	x0, [sp, #344]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #336]
	ldr	x0, [sp, #336]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #320]
	ldr	x0, [sp, #320]
	cbnz	x0, Lrects_overlap_5_phi
	b	Lrects_overlap_4
Lrects_overlap_5_phi:
	mov	x9, #1
	str	x9, [sp, #168]
	b	Lrects_overlap_5
Lrects_overlap_1:
	ldr	w0, [sp, #408]
	sxtw	x0, w0
	str	x0, [sp, #312]
	ldr	x0, [sp, #312]
	ldp	x29, x30, [sp, #448]
	add	sp, sp, #464
	ret
Lrects_overlap_2:
	mov	x0, xzr
	str	w0, [sp, #408]
	b	Lrects_overlap_1
Lrects_overlap_3:
	add	x0, sp, #376
	add	x0, x0, #8
	str	x0, [sp, #296]
	ldr	x0, [sp, #296]
	add	x0, x0, #4
	str	x0, [sp, #288]
	ldr	x0, [sp, #288]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #280]
	add	x0, sp, #392
	add	x0, x0, #4
	str	x0, [sp, #272]
	ldr	x0, [sp, #272]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #264]
	ldr	x0, [sp, #280]
	ldr	x1, [sp, #264]
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #256]
	ldr	x0, [sp, #256]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #248]
	ldr	x0, [sp, #248]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #232]
	ldr	x0, [sp, #232]
	cbnz	x0, Lrects_overlap_9_phi
	b	Lrects_overlap_8
Lrects_overlap_9_phi:
	mov	x9, #1
	str	x9, [sp, #40]
	b	Lrects_overlap_9
Lrects_overlap_4:
	add	x0, sp, #392
	add	x0, x0, #8
	str	x0, [sp, #224]
	ldr	x0, [sp, #224]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #216]
	ldr	w0, [sp, #376]
	sxtw	x0, w0
	str	x0, [sp, #208]
	ldr	x0, [sp, #216]
	ldr	x1, [sp, #208]
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #200]
	ldr	x0, [sp, #200]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #192]
	ldr	x0, [sp, #192]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #176]
	ldr	x9, [sp, #176]
	str	x9, [sp, #168]
	b	Lrects_overlap_5
Lrects_overlap_5:
	ldr	x0, [sp, #168]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #152]
	ldr	x0, [sp, #152]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #136]
	ldr	x0, [sp, #136]
	cbnz	x0, Lrects_overlap_2
	b	Lrects_overlap_3
Lrects_overlap_6:
	mov	x0, xzr
	str	w0, [sp, #408]
	b	Lrects_overlap_1
Lrects_overlap_7:
	mov	x0, #1
	str	w0, [sp, #408]
	b	Lrects_overlap_1
Lrects_overlap_8:
	add	x0, sp, #392
	add	x0, x0, #8
	str	x0, [sp, #112]
	ldr	x0, [sp, #112]
	add	x0, x0, #4
	str	x0, [sp, #104]
	ldr	x0, [sp, #104]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #96]
	add	x0, sp, #376
	add	x0, x0, #4
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #80]
	ldr	x0, [sp, #96]
	ldr	x1, [sp, #80]
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #72]
	ldr	x0, [sp, #72]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #48]
	ldr	x9, [sp, #48]
	str	x9, [sp, #40]
	b	Lrects_overlap_9
Lrects_overlap_9:
	ldr	x0, [sp, #40]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #24]
	ldr	x0, [sp, #24]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	cbnz	x0, Lrects_overlap_6
	b	Lrects_overlap_7

	.globl	_make_color
	.p2align	2
_make_color:
	sub	sp, sp, #160
	stp	x29, x30, [sp, #144]
	add	x29, sp, #144
	str	x0, [sp, #136]
	str	x1, [sp, #128]
	str	x2, [sp, #120]
Lmake_color_0:
	ldr	x0, [sp, #136]
	str	w0, [sp, #80]
	ldr	x0, [sp, #128]
	str	w0, [sp, #72]
	ldr	x0, [sp, #120]
	str	w0, [sp, #64]
	ldr	w0, [sp, #80]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	str	w0, [sp, #88]
	ldr	w0, [sp, #72]
	sxtw	x0, w0
	str	x0, [sp, #48]
	add	x0, sp, #88
	add	x0, x0, #4
	str	x0, [sp, #40]
	ldr	x0, [sp, #48]
	ldr	x1, [sp, #40]
	str	w0, [x1]
	ldr	w0, [sp, #64]
	sxtw	x0, w0
	str	x0, [sp, #32]
	add	x0, sp, #88
	add	x0, x0, #8
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	str	w0, [x1]
	add	x0, sp, #104
	add	x1, sp, #88
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w9, [x1, #8]
	str	w9, [x0, #8]
	b	Lmake_color_1
Lmake_color_1:
	ldr	x9, [sp, #104]
	str	x9, [sp, #8]
	ldr	w9, [sp, #112]
	str	w9, [sp, #16]
	ldr	x0, [sp, #8]
	ldr	x1, [sp, #16]
	ldp	x29, x30, [sp, #144]
	add	sp, sp, #160
	ret

	.globl	_color_mix
	.p2align	2
_color_mix:
	sub	sp, sp, #304
	stp	x29, x30, [sp, #288]
	add	x29, sp, #288
	str	x0, [sp, #272]
	str	x1, [sp, #256]
Lcolor_mix_0:
	add	x0, sp, #208
	ldr	x1, [sp, #272]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w9, [x1, #8]
	str	w9, [x0, #8]
	add	x0, sp, #192
	ldr	x1, [sp, #256]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w9, [x1, #8]
	str	w9, [x0, #8]
	ldr	w0, [sp, #208]
	sxtw	x0, w0
	str	x0, [sp, #184]
	ldr	w0, [sp, #192]
	sxtw	x0, w0
	str	x0, [sp, #176]
	ldr	x0, [sp, #184]
	ldr	x1, [sp, #176]
	add	x0, x0, x1
	str	x0, [sp, #168]
	ldr	x0, [sp, #168]
	mov	x1, #2
	sdiv	x0, x0, x1
	str	x0, [sp, #152]
	ldr	x0, [sp, #152]
	str	w0, [sp, #224]
	add	x0, sp, #208
	add	x0, x0, #4
	str	x0, [sp, #144]
	ldr	x0, [sp, #144]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #136]
	add	x0, sp, #192
	add	x0, x0, #4
	str	x0, [sp, #128]
	ldr	x0, [sp, #128]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #120]
	ldr	x0, [sp, #136]
	ldr	x1, [sp, #120]
	add	x0, x0, x1
	str	x0, [sp, #112]
	ldr	x0, [sp, #112]
	mov	x1, #2
	sdiv	x0, x0, x1
	str	x0, [sp, #96]
	add	x0, sp, #224
	add	x0, x0, #4
	str	x0, [sp, #88]
	ldr	x0, [sp, #96]
	ldr	x1, [sp, #88]
	str	w0, [x1]
	add	x0, sp, #208
	add	x0, x0, #8
	str	x0, [sp, #80]
	ldr	x0, [sp, #80]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #72]
	add	x0, sp, #192
	add	x0, x0, #8
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	x0, [sp, #72]
	ldr	x1, [sp, #56]
	add	x0, x0, x1
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	mov	x1, #2
	sdiv	x0, x0, x1
	str	x0, [sp, #32]
	add	x0, sp, #224
	add	x0, x0, #8
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	str	w0, [x1]
	add	x0, sp, #240
	add	x1, sp, #224
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w9, [x1, #8]
	str	w9, [x0, #8]
	b	Lcolor_mix_1
Lcolor_mix_1:
	ldr	x9, [sp, #240]
	str	x9, [sp, #8]
	ldr	w9, [sp, #248]
	str	w9, [sp, #16]
	ldr	x0, [sp, #8]
	ldr	x1, [sp, #16]
	ldp	x29, x30, [sp, #288]
	add	sp, sp, #304
	ret

	.globl	_color_brightness
	.p2align	2
_color_brightness:
	sub	sp, sp, #144
	stp	x29, x30, [sp, #128]
	add	x29, sp, #128
	str	x0, [sp, #112]
Lcolor_brightness_0:
	add	x0, sp, #88
	ldr	x1, [sp, #112]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w9, [x1, #8]
	str	w9, [x0, #8]
	ldr	w0, [sp, #88]
	sxtw	x0, w0
	str	x0, [sp, #80]
	add	x0, sp, #88
	add	x0, x0, #4
	str	x0, [sp, #72]
	ldr	x0, [sp, #72]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	x0, [sp, #80]
	ldr	x1, [sp, #64]
	add	x0, x0, x1
	str	x0, [sp, #56]
	add	x0, sp, #88
	add	x0, x0, #8
	str	x0, [sp, #48]
	ldr	x0, [sp, #48]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	x0, [sp, #56]
	ldr	x1, [sp, #40]
	add	x0, x0, x1
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	mov	x1, #3
	sdiv	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #104]
	b	Lcolor_brightness_1
Lcolor_brightness_1:
	ldr	w0, [sp, #104]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #128]
	add	sp, sp, #144
	ret

	.globl	_make_pixel
	.p2align	2
_make_pixel:
	sub	sp, sp, #240
	stp	x29, x30, [sp, #224]
	add	x29, sp, #224
	str	x0, [sp, #216]
	str	x1, [sp, #208]
	str	x2, [sp, #200]
	str	x3, [sp, #192]
	str	x4, [sp, #184]
Lmake_pixel_0:
	ldr	x0, [sp, #216]
	str	w0, [sp, #128]
	ldr	x0, [sp, #208]
	str	w0, [sp, #120]
	ldr	x0, [sp, #200]
	str	w0, [sp, #112]
	ldr	x0, [sp, #192]
	str	w0, [sp, #104]
	ldr	x0, [sp, #184]
	str	w0, [sp, #96]
	ldr	w0, [sp, #128]
	sxtw	x0, w0
	str	x0, [sp, #88]
	ldr	w0, [sp, #120]
	sxtw	x0, w0
	str	x0, [sp, #80]
	ldr	x0, [sp, #88]
	ldr	x1, [sp, #80]
	bl	_make_point
	str	x0, [sp, #72]
	add	x0, sp, #136
	add	x1, sp, #72
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w0, [sp, #112]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	w0, [sp, #104]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	x0, [sp, #64]
	ldr	x1, [sp, #56]
	ldr	x2, [sp, #48]
	bl	_make_color
	str	x0, [sp, #32]
	str	x1, [sp, #40]
	add	x0, sp, #136
	add	x0, x0, #8
	str	x0, [sp, #24]
	ldr	x0, [sp, #24]
	add	x1, sp, #32
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w9, [x1, #8]
	str	w9, [x0, #8]
	add	x0, sp, #160
	add	x1, sp, #136
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	ldr	w9, [x1, #16]
	str	w9, [x0, #16]
	b	Lmake_pixel_1
Lmake_pixel_1:
	ldr	x9, [sp, #160]
	str	x9, [sp, #0]
	ldr	x9, [sp, #168]
	str	x9, [sp, #8]
	ldr	w9, [sp, #176]
	str	w9, [sp, #16]
	ldr	x0, [sp, #0]
	ldr	x1, [sp, #8]
	ldp	x29, x30, [sp, #224]
	add	sp, sp, #240
	ret

	.globl	_make_circle
	.p2align	2
_make_circle:
	sub	sp, sp, #160
	stp	x29, x30, [sp, #144]
	add	x29, sp, #144
	str	x0, [sp, #136]
	str	x1, [sp, #128]
	str	x2, [sp, #120]
Lmake_circle_0:
	ldr	x0, [sp, #136]
	str	w0, [sp, #80]
	ldr	x0, [sp, #128]
	str	w0, [sp, #72]
	ldr	x0, [sp, #120]
	str	w0, [sp, #64]
	ldr	w0, [sp, #80]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	w0, [sp, #72]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	x0, [sp, #56]
	ldr	x1, [sp, #48]
	bl	_make_point
	str	x0, [sp, #40]
	add	x0, sp, #88
	add	x1, sp, #40
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w0, [sp, #64]
	sxtw	x0, w0
	str	x0, [sp, #32]
	add	x0, sp, #88
	add	x0, x0, #8
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	str	w0, [x1]
	add	x0, sp, #104
	add	x1, sp, #88
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w9, [x1, #8]
	str	w9, [x0, #8]
	b	Lmake_circle_1
Lmake_circle_1:
	ldr	x9, [sp, #104]
	str	x9, [sp, #8]
	ldr	w9, [sp, #112]
	str	w9, [sp, #16]
	ldr	x0, [sp, #8]
	ldr	x1, [sp, #16]
	ldp	x29, x30, [sp, #144]
	add	sp, sp, #160
	ret

	.globl	_circle_contains
	.p2align	2
_circle_contains:
	sub	sp, sp, #144
	stp	x29, x30, [sp, #128]
	add	x29, sp, #128
	str	x0, [sp, #112]
	str	x1, [sp, #104]
Lcircle_contains_0:
	add	x0, sp, #80
	ldr	x1, [sp, #112]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	w9, [x1, #8]
	str	w9, [x0, #8]
	add	x0, sp, #72
	ldr	x1, [sp, #104]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #80
	add	x1, sp, #72
	bl	_point_dist_sq
	str	x0, [sp, #64]
	add	x0, sp, #80
	add	x0, x0, #8
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #48]
	add	x0, sp, #80
	add	x0, x0, #8
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #48]
	ldr	x1, [sp, #32]
	mul	x0, x0, x1
	str	x0, [sp, #24]
	ldr	x0, [sp, #64]
	ldr	x1, [sp, #24]
	cmp	x0, x1
	cset	x0, le
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #96]
	b	Lcircle_contains_1
Lcircle_contains_1:
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #128]
	add	sp, sp, #144
	ret

	.globl	_make_line
	.p2align	2
_make_line:
	sub	sp, sp, #112
	stp	x29, x30, [sp, #96]
	add	x29, sp, #96
	str	x0, [sp, #88]
	str	x1, [sp, #80]
Lmake_line_0:
	add	x0, sp, #40
	ldr	x1, [sp, #88]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #32
	ldr	x1, [sp, #80]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #48
	add	x1, sp, #40
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #48
	add	x0, x0, #8
	str	x0, [sp, #24]
	ldr	x0, [sp, #24]
	add	x1, sp, #32
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #64
	add	x1, sp, #48
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	b	Lmake_line_1
Lmake_line_1:
	ldr	x9, [sp, #64]
	str	x9, [sp, #8]
	ldr	x9, [sp, #72]
	str	x9, [sp, #16]
	ldr	x0, [sp, #8]
	ldr	x1, [sp, #16]
	ldp	x29, x30, [sp, #96]
	add	sp, sp, #112
	ret

	.globl	_line_length_sq
	.p2align	2
_line_length_sq:
	sub	sp, sp, #80
	stp	x29, x30, [sp, #64]
	add	x29, sp, #64
	str	x0, [sp, #48]
Lline_length_sq_0:
	add	x0, sp, #24
	ldr	x1, [sp, #48]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	add	x0, sp, #24
	add	x0, x0, #8
	str	x0, [sp, #16]
	add	x0, sp, #24
	ldr	x1, [sp, #16]
	bl	_point_dist_sq
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #40]
	b	Lline_length_sq_1
Lline_length_sq_1:
	ldr	w0, [sp, #40]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #64]
	add	sp, sp, #80
	ret

	.globl	_make_triangle
	.p2align	2
_make_triangle:
	sub	sp, sp, #160
	stp	x29, x30, [sp, #144]
	add	x29, sp, #144
	str	x0, [sp, #136]
	str	x1, [sp, #128]
	str	x2, [sp, #120]
Lmake_triangle_0:
	add	x0, sp, #64
	ldr	x1, [sp, #136]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #56
	ldr	x1, [sp, #128]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #48
	ldr	x1, [sp, #120]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #72
	add	x1, sp, #64
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #72
	add	x0, x0, #8
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	add	x1, sp, #56
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #72
	add	x0, x0, #16
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	add	x1, sp, #48
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #96
	add	x1, sp, #72
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	ldr	x9, [x1, #16]
	str	x9, [x0, #16]
	b	Lmake_triangle_1
Lmake_triangle_1:
	ldr	x9, [sp, #96]
	str	x9, [sp, #8]
	ldr	x9, [sp, #104]
	str	x9, [sp, #16]
	ldr	x9, [sp, #112]
	str	x9, [sp, #24]
	ldr	x0, [sp, #8]
	ldr	x1, [sp, #16]
	ldp	x29, x30, [sp, #144]
	add	sp, sp, #160
	ret

	.globl	_triangle_area_2x
	.p2align	2
_triangle_area_2x:
	sub	sp, sp, #400
	stp	x29, x30, [sp, #384]
	add	x29, sp, #384
	str	x0, [sp, #360]
Ltriangle_area_2x_0:
	add	x0, sp, #320
	ldr	x1, [sp, #360]
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	ldr	x9, [x1, #16]
	str	x9, [x0, #16]
	ldr	w0, [sp, #320]
	sxtw	x0, w0
	str	x0, [sp, #312]
	add	x0, sp, #320
	add	x0, x0, #8
	str	x0, [sp, #304]
	ldr	x0, [sp, #304]
	add	x0, x0, #4
	str	x0, [sp, #296]
	ldr	x0, [sp, #296]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #288]
	add	x0, sp, #320
	add	x0, x0, #16
	str	x0, [sp, #280]
	ldr	x0, [sp, #280]
	add	x0, x0, #4
	str	x0, [sp, #272]
	ldr	x0, [sp, #272]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #264]
	ldr	x0, [sp, #288]
	ldr	x1, [sp, #264]
	sub	x0, x0, x1
	str	x0, [sp, #256]
	ldr	x0, [sp, #312]
	ldr	x1, [sp, #256]
	mul	x0, x0, x1
	str	x0, [sp, #248]
	add	x0, sp, #320
	add	x0, x0, #8
	str	x0, [sp, #240]
	ldr	x0, [sp, #240]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #232]
	add	x0, sp, #320
	add	x0, x0, #16
	str	x0, [sp, #224]
	ldr	x0, [sp, #224]
	add	x0, x0, #4
	str	x0, [sp, #216]
	ldr	x0, [sp, #216]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #208]
	add	x0, sp, #320
	add	x0, x0, #4
	str	x0, [sp, #200]
	ldr	x0, [sp, #200]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #192]
	ldr	x0, [sp, #208]
	ldr	x1, [sp, #192]
	sub	x0, x0, x1
	str	x0, [sp, #184]
	ldr	x0, [sp, #232]
	ldr	x1, [sp, #184]
	mul	x0, x0, x1
	str	x0, [sp, #176]
	ldr	x0, [sp, #248]
	ldr	x1, [sp, #176]
	add	x0, x0, x1
	str	x0, [sp, #168]
	add	x0, sp, #320
	add	x0, x0, #16
	str	x0, [sp, #160]
	ldr	x0, [sp, #160]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #152]
	add	x0, sp, #320
	add	x0, x0, #4
	str	x0, [sp, #144]
	ldr	x0, [sp, #144]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #136]
	add	x0, sp, #320
	add	x0, x0, #8
	str	x0, [sp, #128]
	ldr	x0, [sp, #128]
	add	x0, x0, #4
	str	x0, [sp, #120]
	ldr	x0, [sp, #120]
	ldr	w0, [x0]
	sxtw	x0, w0
	str	x0, [sp, #112]
	ldr	x0, [sp, #136]
	ldr	x1, [sp, #112]
	sub	x0, x0, x1
	str	x0, [sp, #104]
	ldr	x0, [sp, #152]
	ldr	x1, [sp, #104]
	mul	x0, x0, x1
	str	x0, [sp, #96]
	ldr	x0, [sp, #168]
	ldr	x1, [sp, #96]
	add	x0, x0, x1
	str	x0, [sp, #88]
	ldr	x0, [sp, #88]
	str	w0, [sp, #344]
	ldr	w0, [sp, #344]
	sxtw	x0, w0
	str	x0, [sp, #80]
	ldr	x0, [sp, #80]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	cbnz	x0, Ltriangle_area_2x_2
	b	Ltriangle_area_2x_3
Ltriangle_area_2x_1:
	ldr	w0, [sp, #352]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	ldp	x29, x30, [sp, #384]
	add	sp, sp, #400
	ret
Ltriangle_area_2x_2:
	ldr	w0, [sp, #344]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #24]
	neg	x0, x0
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #344]
	b	Ltriangle_area_2x_3
Ltriangle_area_2x_3:
	ldr	w0, [sp, #344]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #352]
	b	Ltriangle_area_2x_1

	.globl	_apply_op
	.p2align	2
_apply_op:
	sub	sp, sp, #112
	stp	x29, x30, [sp, #96]
	add	x29, sp, #96
	str	x0, [sp, #88]
	str	x1, [sp, #80]
	str	x2, [sp, #72]
Lapply_op_0:
	ldr	x0, [sp, #88]
	str	x0, [sp, #56]
	ldr	x0, [sp, #80]
	str	w0, [sp, #48]
	ldr	x0, [sp, #72]
	str	w0, [sp, #40]
	ldr	w0, [sp, #48]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	w0, [sp, #40]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #56]
	str	x0, [sp, #16]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	ldr	x16, [sp, #16]
	blr	x16
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	str	w0, [sp, #64]
	b	Lapply_op_1
Lapply_op_1:
	ldr	w0, [sp, #64]
	sxtw	x0, w0
	str	x0, [sp, #0]
	ldr	x0, [sp, #0]
	ldp	x29, x30, [sp, #96]
	add	sp, sp, #112
	ret

	.globl	_my_add
	.p2align	2
_my_add:
	sub	sp, sp, #96
	stp	x29, x30, [sp, #80]
	add	x29, sp, #80
	str	x0, [sp, #72]
	str	x1, [sp, #64]
Lmy_add_0:
	ldr	x0, [sp, #72]
	str	w0, [sp, #48]
	ldr	x0, [sp, #64]
	str	w0, [sp, #40]
	ldr	w0, [sp, #48]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	w0, [sp, #40]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	add	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #56]
	b	Lmy_add_1
Lmy_add_1:
	ldr	w0, [sp, #56]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #80]
	add	sp, sp, #96
	ret

	.globl	_my_mul
	.p2align	2
_my_mul:
	sub	sp, sp, #96
	stp	x29, x30, [sp, #80]
	add	x29, sp, #80
	str	x0, [sp, #72]
	str	x1, [sp, #64]
Lmy_mul_0:
	ldr	x0, [sp, #72]
	str	w0, [sp, #48]
	ldr	x0, [sp, #64]
	str	w0, [sp, #40]
	ldr	w0, [sp, #48]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	w0, [sp, #40]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x0, [sp, #32]
	ldr	x1, [sp, #24]
	mul	x0, x0, x1
	str	x0, [sp, #16]
	ldr	x0, [sp, #16]
	str	w0, [sp, #56]
	b	Lmy_mul_1
Lmy_mul_1:
	ldr	w0, [sp, #56]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldp	x29, x30, [sp, #80]
	add	sp, sp, #96
	ret

	.globl	_my_max
	.p2align	2
_my_max:
	sub	sp, sp, #144
	stp	x29, x30, [sp, #128]
	add	x29, sp, #128
	str	x0, [sp, #120]
	str	x1, [sp, #112]
Lmy_max_0:
	ldr	x0, [sp, #120]
	str	w0, [sp, #96]
	ldr	x0, [sp, #112]
	str	w0, [sp, #88]
	ldr	w0, [sp, #88]
	sxtw	x0, w0
	str	x0, [sp, #80]
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #72]
	ldr	x0, [sp, #80]
	ldr	x1, [sp, #72]
	cmp	x0, x1
	cset	x0, lt
	str	x0, [sp, #64]
	ldr	x0, [sp, #64]
	and	x0, x0, #0xFFFFFFFF
	str	x0, [sp, #56]
	ldr	x0, [sp, #56]
	mov	x1, xzr
	cmp	x0, x1
	cset	x0, ne
	str	x0, [sp, #40]
	ldr	x0, [sp, #40]
	cbnz	x0, Lmy_max_2
	b	Lmy_max_3
Lmy_max_1:
	ldr	w0, [sp, #104]
	sxtw	x0, w0
	str	x0, [sp, #32]
	ldr	x0, [sp, #32]
	ldp	x29, x30, [sp, #128]
	add	sp, sp, #144
	ret
Lmy_max_2:
	ldr	w0, [sp, #96]
	sxtw	x0, w0
	str	x0, [sp, #24]
	ldr	x9, [sp, #24]
	str	x9, [sp, #8]
	b	Lmy_max_4
Lmy_max_3:
	ldr	w0, [sp, #88]
	sxtw	x0, w0
	str	x0, [sp, #16]
	ldr	x9, [sp, #16]
	str	x9, [sp, #8]
	b	Lmy_max_4
Lmy_max_4:
	ldr	x0, [sp, #8]
	str	w0, [sp, #104]
	b	Lmy_max_1

	.globl	_main
	.p2align	2
_main:
	sub	sp, sp, #528
	str	x29, [sp, #512]
	str	x30, [sp, #520]
	add	x29, sp, #512
Lmain_0:
	mov	x0, #20
	str	w0, [sp, #496]
	mov	x0, #22
	str	w0, [sp, #488]
	ldr	w0, [sp, #496]
	sxtw	x0, w0
	str	x0, [sp, #352]
	ldr	w0, [sp, #488]
	sxtw	x0, w0
	str	x0, [sp, #344]
	ldr	x0, [sp, #352]
	ldr	x1, [sp, #344]
	bl	_add_myint
	str	x0, [sp, #336]
	ldr	x0, [sp, #336]
	str	w0, [sp, #480]
	mov	x0, xzr
	mov	x1, xzr
	mov	x2, #10
	mov	x3, #10
	bl	_make_rect
	str	x0, [sp, #288]
	str	x1, [sp, #296]
	add	x0, sp, #464
	add	x1, sp, #288
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	add	x0, sp, #464
	bl	_rect_area
	str	x0, [sp, #280]
	ldr	x0, [sp, #280]
	str	w0, [sp, #456]
	mov	x0, #3
	mov	x1, #4
	bl	_make_point
	str	x0, [sp, #256]
	add	x0, sp, #448
	add	x1, sp, #256
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	mov	x0, xzr
	mov	x1, xzr
	bl	_make_point
	str	x0, [sp, #232]
	add	x0, sp, #440
	add	x1, sp, #232
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	add	x0, sp, #448
	add	x1, sp, #440
	bl	_point_dist_sq
	str	x0, [sp, #224]
	ldr	x0, [sp, #224]
	str	w0, [sp, #432]
	mov	x0, #25
	str	w0, [sp, #424]
	add	x0, sp, #464
	add	x1, sp, #448
	bl	_rect_contains_point
	str	x0, [sp, #208]
	ldr	x0, [sp, #208]
	str	w0, [sp, #416]
	mov	x0, #1
	mov	x1, #1
	bl	_compute_score
	str	x0, [sp, #184]
	ldr	x0, [sp, #184]
	str	w0, [sp, #408]
	mov	x0, xzr
	mov	x1, xzr
	bl	_make_point
	str	x0, [sp, #160]
	mov	x0, #5
	mov	x1, xzr
	bl	_make_point
	str	x0, [sp, #136]
	mov	x0, xzr
	mov	x1, #3
	bl	_make_point
	str	x0, [sp, #112]
	ldr	x0, [sp, #160]
	ldr	x1, [sp, #136]
	ldr	x2, [sp, #112]
	bl	_make_triangle
	str	x0, [sp, #88]
	str	x1, [sp, #96]
	add	x0, sp, #384
	add	x1, sp, #88
	ldr	x9, [x1, #0]
	str	x9, [x0, #0]
	ldr	x9, [x1, #8]
	str	x9, [x0, #8]
	ldr	x9, [x1, #16]
	str	x9, [x0, #16]
	add	x0, sp, #384
	bl	_triangle_area_2x
	str	x0, [sp, #80]
	ldr	x0, [sp, #80]
	str	w0, [sp, #376]
	ldr	w0, [sp, #480]
	sxtw	x0, w0
	str	x0, [sp, #64]
	ldr	w0, [sp, #456]
	sxtw	x0, w0
	str	x0, [sp, #56]
	ldr	w0, [sp, #416]
	sxtw	x0, w0
	str	x0, [sp, #48]
	ldr	w0, [sp, #408]
	sxtw	x0, w0
	str	x0, [sp, #40]
	ldr	w0, [sp, #376]
	sxtw	x0, w0
	str	x0, [sp, #32]
	adrp	x0, _.Lstr.0@PAGE
	add	x0, x0, _.Lstr.0@PAGEOFF
	ldr	x9, [sp, #64]
	ldr	x10, [sp, #56]
	ldr	x11, [sp, #48]
	ldr	x12, [sp, #40]
	ldr	x13, [sp, #32]
	sub	sp, sp, #48
	str	x9, [sp, #0]
	str	x10, [sp, #8]
	str	x11, [sp, #16]
	str	x12, [sp, #24]
	str	x13, [sp, #32]
	bl	_printf
	add	sp, sp, #48
	str	x0, [sp, #24]
	mov	x0, xzr
	str	w0, [sp, #504]
	b	Lmain_1
Lmain_1:
	ldr	w0, [sp, #504]
	sxtw	x0, w0
	str	x0, [sp, #8]
	ldr	x0, [sp, #8]
	ldr	x29, [sp, #512]
	ldr	x30, [sp, #520]
	add	sp, sp, #528
	ret

    .section __TEXT,__cstring,cstring_literals
_.Lstr.0:
    .asciz "%d %d %d %d %d\n\0"

.subsections_via_symbols
